Texture attachment to the wall
seanwu1105/mini-portal-opengl pull request #14
Opened 2022-11-01 18:31 UTC by RaymondHuang210129

2022-11-01 21:32 UTC, seanwu1105 requested changes

2022-11-01 21:32 UTC, seanwu1105 commented on src/shaders/basic.vert
> +layout (location = 1) in vec2 iTextureuv;
I am wondering if this is the naming convention for the UV texture coordinate. If we just want to use camelCase, it should be `iTextureUv` instead. Ignore this if that is a general convention.

2022-11-01 21:32 UTC, seanwu1105 commented on src/texture.ixx
> +export class textureProvider {
To make it consistent, we use capitalized CamelCase for the class name. Feel free to open an issue to rename all class classes to uncapitalized camelCase if you find a good reason to do so.

```suggestion
export class TextureProvider {
```

2022-11-01 21:32 UTC, seanwu1105 commented on src/texture.ixx
> +  mutable std::string _fileName{};
Can be constant.

2022-11-01 21:32 UTC, seanwu1105 commented on src/wall.ixx
> +                          (GLvoid*)offsetof(vertexAttributes, position));
Use `static_cast` instead according to [CppCoreGuideline](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es49-if-you-must-use-a-cast-use-a-named-cast) referenced by [Microsoft](https://learn.microsoft.com/en-us/cpp/code-quality/c26493?view=msvc-170).

2022-11-01 21:32 UTC, seanwu1105 commented on src/wall.ixx
> +  static inline const textureProvider textureProvider{std::move(std::string("textures/tile1.jpeg"))};
Just wondering if we really need move semantic here. Does it have a significant performance gain here? I am not really used to the syntax and it looks like a boilerplate for me. I believe it will be automatically optimized with the release build.

2022-11-01 21:32 UTC, seanwu1105 commented on vcpkg.json
> +    "stb"
Please send a message in the messenger group chat to notify others about the dependency change. Everyone need to rerun `./install.bat` after this is merged.

2022-11-01 22:39 UTC, RaymondHuang210129 commented on src/wall.ixx
> +                          (GLvoid*)offsetof(vertexAttributes, position));
Using `static_cast<GLvoid*>(0)` doesn't show compile error, but `static_cast<GLvoid*>(offsetof(vertexAttributes, position))` does.

2022-11-01 22:52 UTC, seanwu1105 commented on src/wall.ixx
> +                          (GLvoid*)offsetof(vertexAttributes, position));
I mean we should use `static_cast` instead of `(GLvoid*)`. The `offsetof` part is good to go.

2022-11-01 23:11 UTC, RaymondHuang210129 commented on src/wall.ixx
> +                          (GLvoid*)offsetof(vertexAttributes, position));
![image](https://user-images.githubusercontent.com/12983673/199359401-e328ed25-bb73-4763-9619-79a83cc2fce2.png)

I mean this error.

2022-11-02 00:57 UTC, seanwu1105 commented on src/wall.ixx
> +                          (GLvoid*)offsetof(vertexAttributes, position));
Ah, I see. [This solution](https://stackoverflow.com/a/58681133/8789738) might help to mitigate this workaround but I have not tried it. We can just leave it there tho.

2022-11-02 02:59 UTC, RaymondHuang210129 commented on vcpkg.json
> +    "stb"
Will do.

2022-11-02 03:31 UTC, seanwu1105 requested changes

2022-11-02 03:31 UTC, seanwu1105 commented on src/wall.ixx
> +  static inline const TextureProvider textureProvider{std::string("textures/tile1.jpeg")};
```suggestion
  static inline const TextureProvider textureProvider{"textures/tile1.jpeg"};
```

I think we do not need to wrap it with `std::string`, right? (too lazy to really check it on my IDE :) )

2022-11-02 03:37 UTC, RaymondHuang210129 commented on src/wall.ixx
> +  static inline const TextureProvider textureProvider{std::string("textures/tile1.jpeg")};
Yes we need. initialization with braces does not automatically cast to the closest constructor's type. The advantage of using {} is to make everything explicitly.

2022-11-02 04:05 UTC, RaymondHuang210129 commented on src/wall.ixx
> +  static inline const TextureProvider textureProvider{std::string("textures/tile1.jpeg")};
I tried () and it does not work either. If you think I should pass literal instead of string instance, I may change the argument type from string to char*.

2022-11-02 04:26 UTC, seanwu1105 commented on src/wall.ixx
> +  static inline const TextureProvider textureProvider{std::string("textures/tile1.jpeg")};
Oh! I see :)

2022-11-02 04:27 UTC, seanwu1105 approved these changes

2022-11-02 14:54 UTC, merged