feat: build quad-tree-split view
seanwu1105/mini-portal-opengl pull request #24
Opened 2022-11-20 04:06 UTC by seanwu1105

Preview: https://i.imgur.com/EWJ4fS5.mp4

We might want to change the texture of the wall to make it less visually disturbing.

2022-11-20 05:00 UTC, RaymondHuang210129 requested changes

2022-11-20 05:21 UTC, seanwu1105 commented on src/quad-tree.ixx
> +
I cannot get what you are trying to mention here. Could you elaborate it more?

2022-11-21 00:22 UTC, RaymondHuang210129 approved these changes
LGTM

2022-11-21 00:22 UTC, RaymondHuang210129 commented on src/quad-tree.ixx
> +
Seems to be solved, thanks!

2022-11-21 00:32 UTC, sdCaramel302812 approved these changes
lgtm

2022-11-21 00:38 UTC, JoannaWang1216 approved these changes
LGTM

2022-11-21 00:41 UTC, merged